(define (domain m_and_c)
    (:requirements :strips)
    (:types missionary1 missionary2 missionary3 cannibal1 cannibal2 cannibal3 bank1 bank2 boat)
    
    (:predicates
        (on_bank ?obj - (either missionary1 missionary2 missionary3 cannibal1 
            cannibal2 cannibal3) ?bank - (either bank1 bank2))
        (at_bank ?boat - boat ?bank - (either bank1 bank2))
        (same_target ?target1 ?target2 - (either missionary1 missionary2 
            missionary3 cannibal1 cannibal2 cannibal3 bank1 bank2))
    )
    
    (:action one_in_boat
        :parameters (?target - (either missionary1 missionary2 missionary3 cannibal1 
                        cannibal2 cannibal3) ?boat - boat ?from ?to - (either bank1 bank2) 
                        ?m1 - missionary1 ?m2 - missionary2 ?m3 - missionary3 ?c1 - cannibal1 
                        ?c2 - cannibal2 ?c3 - cannibal3 ?b1 - bank1 ?b2 - bank2)
        :precondition   (and
                            (or
                                ;below is 6:0
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                
                                ;below 3 are 5:1
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                ;below 12 are 2:4
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                ;below 2 are 3:3
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                ;below 12 are 4:2
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                
                                ;below 3 are 1:5
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                
                                ;the goal state is not needed here
                            )
                            
                            (not (same_target ?from ?to))
                            (on_bank ?target ?from)
                            (at_bank ?boat ?from)
                        )
        :effect (and
                    (on_bank ?target ?to)
                    (not (on_bank ?target ?from))
                    (at_bank ?boat ?to)
                    (not (at_bank ?boat ?from))
                )
    )
    
    (:action two_in_boat
        :parameters (?target1 ?target2 - (either missionary1 missionary2 missionary3 
                        cannibal1 cannibal2 cannibal3) ?boat - boat ?from ?to - (either bank1 bank2) 
                        ?m1 - missionary1 ?m2 - missionary2 ?m3 - missionary3 ?c1 - cannibal1 
                        ?c2 - cannibal2 ?c3 - cannibal3 ?b1 - bank1 ?b2 - bank2)
        :precondition   (and
                            (or
                                ;below is 6:0
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                
                                ;below 3 are 5:1
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                ;below 12 are 2:4
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                ;below 2 are 3:3
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                
                                ;below 12 are 4:2
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b1)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b1)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b1)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b1)
                                )
                                
                                ;below 3 are 1:5
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b1)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b1)
                                    (on_bank ?c3 ?b2)
                                )
                                (and
                                    (on_bank ?m1 ?b2)
                                    (on_bank ?m2 ?b2)
                                    (on_bank ?m3 ?b2)
                                    (on_bank ?c1 ?b2)
                                    (on_bank ?c2 ?b2)
                                    (on_bank ?c3 ?b1)
                                )
                                
                                ;the goal state is not needed here
                            )
                            (not (same_target ?target1 ?target2))
                            (not (same_target ?from ?to))
                            (on_bank ?target1 ?from)
                            (on_bank ?target2 ?from)
                            (at_bank ?boat ?from)
                        )
        :effect (and
                    (on_bank ?target1 ?to)
                    (not (on_bank ?target1 ?from))
                    (on_bank ?target2 ?to)
                    (not (on_bank ?target2 ?from))
                    (at_bank ?boat ?to)
                    (not (at_bank ?boat ?from))
                )
    )
)
