# Generated by Django 2.0.5 on 2018-05-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PddLparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pddl',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
