(define (problem blocksworld-40-0)
(:domain blocksworld)
(:objects d o c t m h w n j1 h1 a m1 j g1 i1 q b p l v
          f1 y k1 n1 d1 z x s e c1 r u k e1 b1 g a1 f i l1)
(:init (clear d) (clear o) (clear c) (clear t) (clear m)
                    (clear h) (on-table d) (on-table w) (on-table n) (on-table t)
                    (on-table m) (on-table h) (on o j1) (on j1 h1) (on h1 a)
                    (on a m1) (on m1 j) (on j g1) (on g1 i1) (on i1 q)
                    (on q b) (on b p) (on p l) (on l v) (on v f1) (on f1 y)
                    (on y k1) (on k1 n1) (on n1 d1) (on d1 z) (on z x)
                    (on x s) (on s e) (on e c1) (on c1 r) (on r u) (on u k)
                    (on k e1) (on e1 b1) (on b1 g) (on g w) (on c a1)
                    (on a1 f) (on f i) (on i l1) (on l1 n) (arm-free))
(:goal (and (on a b1) (on b1 s) (on s i1) (on i1 a1) (on a1 y) (on y r)
           (on r k) (on k j1) (on j1 d) (on d n) (on n f) (on f g) (on g e)
           (on e n1) (on n1 t) (on t u) (on u c) (on c l1) (on l1 d1)
           (on d1 p) (on p v) (on v q) (on q m1) (on m1 h) (on h k1)
           (on k1 e1) (on e1 w) (on w f1) (on f1 o) (on o j) (on j z)
           (on z c1) (on c1 m) (on m x) (on x l) (on l h1) (on h1 b) (on b i)
           (on i g1)))
)