(define (problem blocksworld-30-0)
(:domain blocksworld)
(:objects v b y s c f a z d i h x t b1 w q g r o l a1 k c1 n m e d1 u j p )
(:init (clear p) (clear j) (clear u) (clear d1) (clear e) (clear m) (clear n)
 (on-table p) (on-table c1) (on-table k) (on-table a1) (on-table l) (on-table o)
 (on-table n) (on j r) (on r g) (on g q) (on q w) (on w b1) (on b1 t) (on t c1)
 (on u x) (on x k) (on d1 h) (on h i) (on i d) (on d z) (on z a) (on a f)
 (on f c) (on c a1) (on e s) (on s y) (on y b) (on b v) (on v l) (on m o)
 (arm-free))
(:goal (and (on c1 i) (on i x) (on x h) (on h u) (on u b1) (on b1 k) (on k a)
            (on a n) (on n d) (on d e) (on e o) (on o r) (on r v) (on v d1)
            (on d1 f) (on f j) (on j t) (on t m) (on m p) (on p s) (on s a1)
            (on a1 y) (on y z) (on z c) (on c w) (on w g) (on g q) (on q b)
            (on b l)))
)